<?php echo \Phalcon\Tag::javascriptInclude("js/main.js"); ?>
<table class="table table-striped"  id="user-list">
  <thead>
    <tr>
      <th scope="col">User id</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">User type</th>
      <th scope="col">Created at</th>
    </tr>
  </thead>
  <tbody>

  </tbody>
</table>
