<?php echo \Phalcon\Tag::javascriptInclude("js/address.js"); ?>

<div class="container">
    <ul class="nav nav-tabs my-3">
    <li class="nav-item">
      <a data-toggle="tab" class="active show nav-link" href="#list">List</a>
    </li>
    <li class="nav-item">
      <a data-toggle="tab" class="nav-link" href="#create">Create</a>
    </li>
  </ul>
      <div class="tab-content">
      <div id="list" class="tab-pane fade in active show">
        <table class="table table-striped"  id="user-list">
          <thead>
            <tr>
              <th scope="col">Address id</th>
              <th scope="col">User id</th>
              <th scope="col">City</th>
              <th scope="col">Postcode</th>
              <th scope="col">Region</th>
              <th scope="col">Street</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
      <div id="create" class="tab-pane fade">
        <form action="/user/createAddress" method="POST">
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputcity4">City</label>
              <input required name="city" type="text" class="form-control" id="inputCity4" placeholder="">
              <input name="user_id" id="user_id" hidden>
            </div>
            <div class="form-group col-md-6">
              <label for="inputPostcode4">Postcode</label>
              <input required name="postcode" type="text" class="form-control" id="inputPostcodel4" placeholder="">
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputRegion4">Region</label>
              <input required name="region" type="text" class="form-control" id="inputRegion4" placeholder="">
            </div>
            <div class="form-group col-md-6">
              <label for="inputStreet4">Street</label>
              <input required  name="street" type="text" class="form-control" id="inputStreet4" placeholder="">
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Create</button>
          </form>
          <?php $this->flashSession->output() ?>
      </div>
    </div>
</div>